# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY   # <- supprime l'erreur "service_account requires logging"

substitutions:
  _AR_IMAGE: us-central1-docker.pkg.dev/nimble-chimera-247619/jobs-preopt/preopt
  _TAG: $SHORT_SHA

steps:
- name: gcr.io/cloud-builders/docker
  args: ['build','-t','${_AR_IMAGE}:${_TAG}','.']

images:
- '${_AR_IMAGE}:${_TAG}'
